### ISSUE TITLE
compiler->pos not initialized.

### ISSUE THREAD

**Issue by pawkw** [nibblebits/PeachCompiler#1]
compiler->pos.line and compiler->pos.col are not initialized. This causes compiler_error and compiler_warning in the file compiler.c to be off by one. This can be tested by compiling the latest version of PeachCompiler and inserting a `$` as the very first character in the file.

**Comment by nibblebits** [comment]
Hi
I can confirm that this is initialized in a later lecture. I have just checked
Thanks

**Comment by nibblebits** [comment]
Hi
I have reopened the issue as I was looking at Dragon Compiler source code not Peach Compiler. This needs to be done here I will create a new lecture to fix it
Thanks

**Comment by nibblebits** [comment]
To confirm as I went to fix this bug today it turns out not to be an issue because having them set to 1 results in the error line numebr to be one greater than it should, the same for column. It could be argued a better design would be to change where the line number is incremented, thus setting it at 1 at the creation would make sense. But as this is not a bug the issue is closed. Though I agree a better design would be to set them to 1 and ensure theirs no off by one during error output.

Thanks
